# =====================
# SPRING BOOT GENERAL
# =====================
spring.application.name=${SPRING_APPLICATION_NAME}

# =====================
# MySQL CONFIGURACION
# =====================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA (solo MySQL)
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}

# =====================
# MongoDB CONFIGURACION
# =====================
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# =====================
# THYMELEAF
# =====================
spring.thymeleaf.prefix=${SPRING_THYMELEAF_PREFIX}
spring.thymeleaf.suffix=${SPRING_THYMELEAF_SUFFIX}
spring.thymeleaf.check-template-location=${SPRING_THYMELEAF_CHECK_TEMPLATE_LOCATION}

# =====================
# MULTIPART / ARCHIVOS
# =====================
spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE}