# =====================
# SPRING BOOT GENERAL
# =====================
spring.application.name=${SPRING_APPLICATION_NAME}

# =====================
# MySQL CONFIGURACI�N
# =====================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

# IA
spring.ai.model.chat=ollama
spring.ai.ollama.base-url=${OPENAI_BASE_URL:"http://localhost:11434/"}
spring.ai.ollama.chat.options.model=${OPENAI_MODEL:"phi3:latest"}
spring.ai.ollama.chat.options.temperature=0.2
app.ai.negacion="No puedo responder esa pregunta"

# =====================
# JPA (solo MySQL)
# =====================
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}

# =====================
# MongoDB CONFIGURACI�N
# =====================
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# =====================
# SPRING SECURITY
# =====================
spring.security.user.name=${SPRING_SECURITY_USER_NAME}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD}

# =====================
# THYMELEAF
# =====================
spring.thymeleaf.prefix=${SPRING_THYMELEAF_PREFIX}
spring.thymeleaf.suffix=${SPRING_THYMELEAF_SUFFIX}
spring.thymeleaf.check-template-location=${SPRING_THYMELEAF_CHECK_TEMPLATE_LOCATION}

# =====================
# MULTIPART / ARCHIVOS
# =====================
spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE}